# mpc
receding: 5
step_time: 0.3
ref_speed: 0.3
device: 'cpu'
time_print: False
collision_threshold: 0.01

# robot
robot:
  kinematics: 'diff'
  max_speed: [0.5, 1.5]
  max_acce: [0.5, 1.5]
  length: 0.322
  width: 0.22

ipath:
  interval: 0.09
  waypoints: [[0.43, 0, 0], [0.8, 0.2698, 0], [1.5, 0.2386, 0], [1.5, -0.6186, 0], [-0.86808, -0.62198, 0], [-0.8079, 1.67594, 0], [0.48036, 1.6949, 0], [0.52413, 0.6217, 0]]
  curve_style: 'line'
  min_radius: 0.0
  loop: True
  arrive_threshold: 0.5
  close_threshold: 0.1
  arrive_index_threshold: 3

# proximal alternating minimization network
pan:
  iter_num: 2
  dune_max_num: 100
  nrmp_max_num: 10
  dune_checkpoint: None
  iter_threshold: 0.1

# adjust parameters
adjust:
  q_s: 0.3
  p_u: 2.5
  eta: 10.0
  d_max: 0.01
  d_min: 0.005